### ISSUE TITLE
Bluedog Design Bureau 1.9 To-Do

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#1139]
- [x] Finish peacekeeper texture touchups
- [x] Finish Titan SRB touchups
- [x] Finish Pioneer configs
- [x] Write multispectral sci def
- [x] Fix Pioneer Texture Sheet 1
- [x] Neptune camera node fix for pioneer
- [x] Finish Clementine names/descriptions
- [x] Additional RAE decoupler
- [x] Kill old Mercury chute
- [x] Fix Titan 23G Adapter
- [x] Fix normals on mesh of LDC short adapter (they are fucked up)
- [x] Probe Science Parts Cargo Values
- [x] Replace xmitDataScalar w/ scienceValueRatio and totalScienceLevel
