### ISSUE TITLE
Cobalt's 1.11 ToDo

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#1288]
- [ ] Final pass on AES LM variants
- [x] Fold out LM RTG
- [x] flush mount LM RTG
- [x] Sample Storage Container (surface part)
- [x] Apollo Lunar Surface Drill (manual scientist operated deployable drill)
- [x] Surface Electrical Properties experiment (ground Deployable half of LRV)
- [x] Kadley telescope
- [x] Lunar Self Recording Penetrometer (missing LRV experiment)
- [x] 100ft drill
- [x] S-IV/Centaur adapter
- [x] Lunar Flying Vehicle
- [x] SA-500F texture switch
- [x] Nuclear interstages
- [x] Handle color switch for CSM decoupler (and SM?)
- [x] Look into white variant for miscparts texture.
- [x] Cylindrical Big G
- [x] Add airlock window to LM shelter
- [x] #1322 
- [x] LR-87/91 
- [ ] SheLab/LTV

**Comment by Rodg88** [comment]
Needs fixes: #1285, #1261

**Comment by Rodg88** [comment]
On models with foil switching, like lm descent tanks, legs, q3 storage, and cockpits, if the meshes with the mapped spec shader can get unique names that would be good. I can then work around a minor bug in B9 specular map switching.

**Comment by CobaltWolf** [comment]
Alright should be doable

**Comment by Rodg88** [comment]
#1292

**Comment by Rodg88** [comment]
#1294

**Comment by Rodg88** [comment]
Re the foil meshes: only the LM descent tanks and Q3 storage need renames. The Legs/MESA/Ascent stages have all been fixed in config and don't need model updates. #1296

**Comment by Rodg88** [comment]
#1316 big g Apollo endcaps

**Comment by Rodg88** [comment]
Reminder to add airlock to shelter
