### ISSUE TITLE
Zorg's 1.11 todo list

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#1289]
- [x] Comet expanded fairing
- [x] 2.5m fairing ring
- [x] New 2.5m fairing for reverse launched CM
- [x] Tweaks to power tower base
- [x] See if dual solar array is feasible for power tower solars
- [x] Finalise system heat balance
~~integrate SWE effects for sep motors~~
- [x] Some WF plume fixes
- [x] standalone handrail variants
- [x] Hollow/hatchless/docking ring only variant for CADS port
- [x] Ring version of 6.25m fairing base. Consolidate fairing and SLA mus
- [x] Add system heat and deployable engines to CKAN

**Comment by zorg2044** [comment]
ecc0e3ea6555990da8575cded31e5eef0ec8b541

**Comment by PickledTripod** [comment]
Hollow/hatchless/docking ring only variant for CADS port
