### ISSUE TITLE
Saturn to-do

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#176]
- [x] Fix flagDecal UVs
- [x] Switch Saturn 1B Interstage to newer interior style
- [x] Add retros to the S-1C engine mount
- [x] Increase node size in the S-1C engine mount's F1 placements
- [x] Disable omni decoupling on the S-II interstage
- [x] Increase heat tolerance of the S-II Ullage motors to prevent them exploding after catching engine wash.

(Need to add more as I find them)

**Comment by Modsojoy** [comment]
Quick Question - any chance that you could add me on as a Collaborator, I'd love to help out since i have 10 out of the 24 hours in a day to do whatever.

**Comment by CobaltWolf** [comment]
You can do all that via PRs. You don't need to be a collaborator to contribute. :)

**Comment by Modsojoy** [comment]
Ah, alright then, I was just suggesting distributing the Work a bit more, Such as updates and Multiple Fix jobs like this thread.

**Comment by CobaltWolf** [comment]
Well, anyone can work on stuff. We have a fairly long history of contributors helping us with the massive pile of work that is always mysteriously left the day before we want to update.

**Comment by Modsojoy** [comment]
Things that involve Unity?

**Comment by CobaltWolf** [comment]
Things that involve Unity can only be solved on my end anyways, since it'd be too much of a pain to rebuild the scene files?

**Comment by Modsojoy** [comment]
you can just save the File to a .unity project

**Comment by CobaltWolf** [comment]
Well, I don't really need help with all the Unity stuff. It's more things like making sure all the compatibility files get properly updated for stuff like Tweakscale, things are properly tagged, tech tree placement, making sure everything has a proper name and description

**Comment by Modsojoy** [comment]
Ah.
