### ISSUE TITLE
RELEASE DAY CHECKLIST

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#228]
- [x] Convert textures to DDS
- [x] Update CRP
- [x] Update credits 
- [x] Update changelog
- [x] Update OP
- [x] Package zip file
- [x] Upload to Spacedock 
- [x] Write long, sappy post
- [x] List known issues - wobbly Saturn, etc
- [x] Update thread title
- [x] Get thread moved to Add On Releases
- [x] Make shitpost on Reddit

People to thank: too many

**Comment by IronCretin** [comment]
Wobbly Saturn is mostly fixed.

**Comment by Modsojoy** [comment]
Ayyylmao. I have to redo the Mesh for the LEM Cockpit. so just checking - Release day does not = No more adding/removing stuff? Or am i misinterpreting this entire thread.

**Comment by CobaltWolf** [comment]
It's our 1.0 release. Everything after this is stretch goals + making it better. Nothing much changes except maybe holding ourselves to a higher standard.

**Comment by Modsojoy** [comment]
So, i can('t)? Update the LEM's internals?

**Comment by CobaltWolf** [comment]
Work will continue as normal. We're just moving forward with release; everything can continue to be improved / updated / added. There will be a v1.1, v1.2 etc.

**Comment by Modsojoy** [comment]
Kk.

**Comment by CobaltWolf** [comment]
Just gotta wait for Spacedock to add 1.2 tags...
