### ISSUE TITLE
Agena ToDo

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#327]
Cobalt's ToDo for the Agena textures
- [x] AO on Agena D trusses
- [x] Generally more detail around Agena D engine
- [x] Fairing texture
- [x] Agena A detail
- [x] Agena Materials Bay (WIP, just needs a cleanup)
- [x] Also, make the black panels on Gemini slightly shiny
