### ISSUE TITLE
Final checklist for BDB v1.5

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#524]
Please excuse the mess, I just don't want to forget anything...

- [x] Delta interstage textures (the autoshroud was all messed up and the interstage itself has no textures on the interior)
- [x] Upload reverted Titan solid models and textures (not cfgs, I already fixed this in my local Gamedata)
- [x] Solve #443 (we were talking on Discord and it should be simple)
- [ ] Remove LDC from release before zipping
- [x] Figure out if something is broken with the PBV, Castor, and short Algol RealPlumes
- [x] Upload E-1A configs (working in my gamedata already, need to upload)
- [ ] Check dependencies

**Comment by CobaltWolf** [comment]
@jsolson confirmed that the plume fix worked, good job. :)

**Comment by CobaltWolf** [comment]
Attempt to fix #443 was unsuccessful, I'm not going to let it prevent us from pushing a release.
