### ISSUE TITLE
GATV/ATDA To-Do

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#831]
- [ ] Get fairings to decouple successfully (adjust colliders, maybe add separation thrusters?)
- [ ] Trim length of TDA Status Panel animations to hopefully make it impossible to desync them
- [ ] Fix docking port - make animation just for fun?
- [ ] Fix running light attach (somehow)
- [ ] fix docking port orientation? Somehow?

**Comment by jsolson** [comment]
If shielding is important, use the [SLA Base](https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Parts/Saturn/bluedog_Saturn_S4B_SLAbase.cfg) as the template for the fairings. The decouplers need to be on the base, and ModuleBdbSLAHelper will provide the DeployModule that ModuleCargoBay needs.

**Comment by CobaltWolf** [comment]
u h

**Comment by CobaltWolf** [comment]
Add a one frame scale animation to the emission cards for the lights
