### ISSUE TITLE
SAF fairings roadmap

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#844]
Titan
- [x] III-E (1.875 > 2.6m)
- [x] **CT3 (1.875 > 2.5m)** [fix normals]
- [x] CT3 Speltra dual adapter (2.5m)
- [x] Titan IV (1.875 > 3.125m)
- [x] Titan III standard fairing (1.875m)
- [x] Titan III-A/C conical fairing (brown) (1.875m)
- [x] Hexagon/ 33B/Seasat biconic fairing (1.875m)
- [x] 33B/Seasat Agena Adapter fairing base (1.875-0.9375)

LDC
- [x] Re-use Titan IV for the flat 3.125m base (3.125m)
- [x] 3.125m to 3.5m adapter boattail so LDC can use the Atlas fairing (either separate part or built into the atlas SAF)
- [x]Scaled up Titan IV for 3.125m to 3.5m adapter

Delta
- [x] Delta II 9.5 foot (irl) metal fairing (1.5m)
- [x] Delta K 1.875m non historical fairing (using Titan III standard fairing model)
- [x] Delta II composite fairing short version. (1.5m)
- [x] Delta II composite fairing long version
- [x] Straight 8 (1.5m) (also use for the flat 1.5m base?)
- [x] 1.5m - 1.875m fairing base for use with Titan 3C shroud.

Variant ideas
- [x] straight 8 w blue nose ( plus non historical blue and blue&white combos for the other configs)
 
Able/Delta B
- [x] Able bulbous fairing (0.625m flared) Pioneer P3 style
- [x] Able bulbous fairing (0.625m flared) smooth qtip style (mostly Atlas Able?)
- [x] Able bulbous fairing (0.625m flared) Flatter top style (thor able?)
- [x] Able hemispherical low drag fairing (0.625m)
- [x] Able conical low drag fairing (0.625m)
- [x] Ablestar (custom size) [check UV padding for mip map issues]
- [x] Ablestar (scaled for 0.9375m standard fairing)

Vanguard
- [x] vanguard fairing with custom base (0.625m)

Scout
- [x] Scout/ Thor Burner 1 (0.625m)
- [x] Scout long fairing (0.625m)

Peacekeeper/Athena/Minotaur/Carrack
- [x] 1.5m carrack adapter base (use delta straight 8 model)

Juno
- [x] Juno II historical - fixed 0.9375m tapered base with >0.625 cone.
- [x] 0.9375m conical pointy fairing with standard base for Juno IV 6K etc.
- [x] 1.25m conical pointy fairing with standard base for Juno IV 45K & redstone derivatives etc.
All 3 to use similar style and share textures.

Agena
- [x] Lunar orbiter (0.9375 > 0.98m)
- [x] Ranger (0.9375 > 1.1m)
- [x] Standard fairing (0.9375 > 0.95m?)
- [x] SLV3B OAO fairing with base. (1.875m) [add optional attach node so it can be a standalone base]

Centaur/Vega
- [x] Atlas Centaur Prototype shroud
- [x] Atlas Centaur Standard shroud (1.875m) (shared textures with Agena OAO)
- [x] Vega

Atlas V
- [x] 4m (2.5m) (same as Atlas II & III? v similar at any rate)
- [x] 5m (3.5m)

Issues
- [ ] Check thermal limits

**Comment by CobaltWolf** [comment]
Straight Eight fairing? That was used all the way up through some early Delta II launches

**Comment by Pappystein** [comment]
Just wanted to comment.  I love these new fairings.  So THANKS!
