### ISSUE TITLE
Mercury To-Do

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#845]
Cobalt:
- [x] Model new bag for the parachute now that its a separate part
- [x] texturing inside of decoupler ring
- [x] texturing base of capsule
- [x] texturing top of heatshield
- [x] texturing interior of nose cone
- [x] Texturing on retro rockets
- [x] Some missing areas of texture on the LES
- [x] Add cameraTransform to periscope for HullCam compatibility
- [x] Add recovery beacon light to the recovery aids animation (already modeled just doesn't do anything)
- [x] 80% length 1.25m adapter tank for Atlas (make it as a third option?) to get the proportion right
- [x] make abortTransform less lopsided
- [x] Make jettison thrustTransforms straight

Jso/Zorg/whomever:
- [x] Adjust buoyancy of the pod to make sure it floats in the right orientation
- [ ] ~~If we're going to have the nose be an air brake, test to make sure it properly serves its purpose of preventing the capsule from reentering nose first~~
- [x] Get the jettison on the retro SRBs fixed
- [ ] Make the "Enhanced" retro pack have... some benefit? Battery and maybe monoprop?
- [ ] Add Hullcam compatibility once cameraTransform is in
- [ ] Figure out some way to make it so the mystery goo door can be closed for reentry without losing the data. Might have to convert to DMagicScienceAnimate, don't know if that will cause Animation Layer issues like the parachutes
- [x] General balance pass for mass, resources, parachute drags, SRB stats, etc.

**Comment by jsolson** [comment]
Need the angle on the LES abortTransfrom reduced a lot. The sep motor can be straight up.

**Comment by jsolson** [comment]
I'd ditch the airbrake and go with the drogue chute.

**Comment by CobaltWolf** [comment]
I don't know what you mean by "ditch the air brake". That's the only way I could get the flap on the nose to deploy without breaking the parachute. It's not hurting anything to have it and like I said, if its even possible to reenter the right way maybe it could help. Might be useful if the player reenters after consuming all the mono.

**Comment by CobaltWolf** [comment]
Why would the sep motor go straight up? Wouldn't that just lead to a recontact? I can reduce the angle on the abortTransform

**Comment by Pappystein** [comment]
> Why would the sep motor go straight up? Wouldn't that just lead to a recontact? 

I don' t know if you have this answer already but: Short answer is Orbital Mechanics... LES is going faster therefor it is, positionally it is HIGHER even though it flew straight ahead of the Rocket stack. Also the Rocket stack while under thrust on the climb-out from launch is CONSTANTLY changing AOA to the horizon.
